site_name: CSEL1
site_description: Construction de systèmes embarqués sous Linux
copyright: "Copyright &copy; 2022 Haute école d'ingénierie et d'architecture of Fribourg"
site_url: https://mse-csel.github.io/website/

docs_dir: '../docs/'
site_dir: '../public/'

theme:
  name: material
  language: 'fr'
  font:
    text: 'Roboto'
    code: 'IBM Plex Mono'
  custom_dir: '../overrides/'
  icon:
    logo: material/school 
  favicon: 'assets/images/favicon.ico'
  features:
    - content.code.annotate
    - navigation.sections

markdown_extensions:
  - admonition
  - extra
  - smarty:
      smart_angled_quotes: true
      substitutions:
        left-angle-quote: "&laquo;&#xA0;"
        right-angle-quote: "&#xA0;&raquo;"
  - mkdcomments
  - footnotes
  - codehilite
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - mdx_math
  - pymdown_include
  - attr_list

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  Ado: Architecture des ordinateurs
  ado: architecture des ordinateurs
  class_names:
    - ISC-2
  year: '2021-2022'
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mse-csel/website
