INHERIT: base.yml
site_url: https://mse-csel.github.io/website
site_name: Construction de systèmes embarqués sous Linux
site_description:  Construction de systèmes embarqués sous Linux
copyright: "Copyright &copy; 2023 Haute école d'ingénierie et d'architecture of Fribourg"

extra:
  teacher_name: "Jacques Supcik"
  year: '2022-2023'
  teams_code: mx5fntd
  info:
    students_count: 12
    students_cs: 11
    students_ds: 1
    students_ft: 2
    students_pt: 10

  pdf_to_jpg:
    programmation-noyau/modules/assets/sp.03.1_mas_csel_noyau_modules.pdf
  social:
    - icon: material/web
      link: https://www.msengineering.ch/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/hesso/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hes_so
    - icon: fontawesome/brands/linkedin
      link: https://ch.linkedin.com/school/university-of-applied-sciences-western-switzerland/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/hessoeducation/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/hessofilms
