INHERIT: base-fr.yml
site_url: https://mse-csel.github.io/website
site_name: Construction de systèmes embarqués sous Linux
site_description:  Construction de systèmes embarqués sous Linux


extra:
  teacher_name: "Jacques Supcik"
          
