name: publish-websites

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
env:
  SELECT_FILE_CONDITION: 999
  SHOW_SOLUTION: 999
  ENABLE_PDF_EXPORT: 0

jobs:
  build-and-push-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build mkdocs site
        uses: ./.github/actions/mkdocs-edu
        with:
          published-week: "5"
          published-solutions: "4"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public